language: r
r:
  - 3.3.0
  - release
  - devel

sudo: required

cran: http://cran.rstudio.com

cache:
  packages: true

r_build_args: "--no-build-vignettes"
r_check_args: "--as-cran --no-build-vignettes --no-vignettes"

r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

